name: 'Release'

on:
  push:
    tags:

jobs:
  github:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Extract release note
        run: |
          ruby \
            -e 'print("## MyQuiver "); \
                puts(ARGF.read.split(/^## /)[1].gsub(/ {.+?}/, ""))' \
            NEWS.md > release-note.md
      - name: Upload to release
        run: |
          gh release create \
            --discussion-category Announcements \
            --notes-file release-node.md
        env:
          GH_TOKEN: ${{ github.token }}
